modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "bigcontraptions"
version = "${version}"
displayName = "Create: Big Contraptions"
authors = "MuriPlz"
description = '''
Increases NBT size limit (2MB -> 10MB) in your playerdata
'''
#logoFile = ""

[[dependencies.bigcontraptions]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.bigcontraptions]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"