# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
# Mod properties
mod_version=1.0
maven_group=com.kryeit
archives_name=bigcontraptions
enabled_platforms=fabric,neoforge
# Minecraft properties
minecraft_version=1.21.1
# Dependencies
architectury_api_version=13.0.8
fabric_loader_version=0.17.2
fabric_api_version=0.116.6+1.21.1
neoforge_version=21.1.209
