modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "bigcontraptions"
version = "${version}"
displayName = "Create: Big Contraptions"
authors = "MuriPlz"
description = '''
Render and hold big contraptions
'''
#logoFile = ""

[[dependencies.bigcontraptions]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.bigcontraptions]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "bigcontraptions.mixins.json"
